### PR TITLE
Eval function( would you like? and are these code allowed?)

### PR DESCRIPTION
**Pull request by sitifukujin**
Would you like to have simple eval.py?
Original sources were on mitmul-san's chainer-faster-rcnn.
(Now, it disappears at v2)
Could you accept these non-original sources?
(I customized them to run on Python and Windows ).

Honestly saying, I don't know good manners on GITHUB included MIT license.
Any advice helps me even if you don't accept this pull request.
Thanks.

### CODE REVIEW

**Comment by Hakuyume** [comment]
@sitifukujin Actually, I am developing ChainerCV (https://github.com/chainer/chainercv), which is a library for computer vision tasks. ChainerCV contains SSD and evaluation codes. This library is much better than my chainer-ssd because it is documented and tested well.

**Comment by sitifukujin** [comment]
Yes, I know you are dedication to chainercv.
And also I am expecting chainercv strongly.
But, I want to contribute any thing. I think these pull request ( include SSD512) are my last contributes. 
I would like to say again. Thank you very much.

**Comment by Hakuyume** [comment]
> But, I want to contribute any thing. I think these pull request ( include SSD512) are my last contributes.

I want to migrate to ChainerCV and freeze this repository. If you want to contribute, could you send PRs to ChainerCV?

**Comment by sitifukujin** [comment]
>If you want to contribute, could you send PRs to ChainerCV?

Uhm, I have not read and use chainercv yet.
But it seems to take many time to understand how to contribute that.
I wish you reuse my small pulls requests somewhere and get speed up to implement chainercv or future working.

Of course, when I find what I can contribute on chaiercv, I will send other PRs.

**Comment by Hakuyume** [comment]
> I wish you reuse my small pulls requests somewhere and get speed up to implement chainercv or future working.
 
Thank you. But the improvements you sent are already done in ChainerCV.
Actually, there is no training result of SSD512 in ChainerCV. However, I can't use your result because my code in this repository has bugs.

**Comment by sitifukujin** [comment]
Don't worry. It's ok for me.
Oh, that is unofficial-unofficial record lol.
Thank you, see you again.

**Pull request closed without merging**
