### PR TITLE
Support Chainer 2.0.1 and 3.0.0a1

### PR DESCRIPTION
**Pull request by kkebo**
`chainer.links.caffe.CaffeFunction.add_link` has been [deprecated](https://docs.chainer.org/en/latest/reference/generated/chainer.links.caffe.CaffeFunction.html#chainer.links.caffe.CaffeFunction.add_link) since 2.0.0, and `chainer.links.caffe.CaffeFunction` no longer calls `self.add_link` since [this commit](https://github.com/chainer/chainer/pull/2947/files) was merged.

I switched from overriding `add_link` to overriding `__setattr__` so that it can run in Chainer 2.0.1 or later.

### CODE REVIEW

**Comment by Hakuyume** [comment]
@kkk669 
Thank you. Could you send this PR to [ChainerCV](https://github.com/chainer/chainercv)?

**Comment by kkk669** [comment]
I see. I'll do that. Thank you.

**Comment by kkebo** [comment]
I see. I'll do that. Thank you.

**Comment by Hakuyume** [comment]
@kkk669 Thank you for updating this PR. But I would like to freeze this repository. Please send new features and improvements to ChainerCV.

**Pull request closed without merging**
